title: Hello, world! I'm David Freeman
description: > # this means to ignore newlines until "baseurl:"
Technologiami informacyjnymi pasjonuję się od ponad 20 lat, jest to moje hobby oraz mój zawód.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://mimachniak.github.io/sysopslife " # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Michał Machniak # add your name
author-img: david-freeman.jpg # add your photo
about-author: I am a web developer focusing on front-end development. Always hungry to keep learning. # add description
social-twitter: MichalMachniak # add your Twitter handle
social-facebook: michal.machniak # add your Facebook handle
social-github: mimachniak # add your Github handle
social-linkedin: michal-machniak # add your Linkedin handle
social-email: mmachniak@oulook.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
