title: sysOps /devOps daily life ... with Michal Machniak
description: > # this means to ignore newlines until "baseurl:"
  Blog dedicated to Microsoft technologies, based on my daily 
  experience of working as sysOps / devOps / System Architect.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://mimachniak.github.io/sysopslife" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Michał Machniak # add your name
author-img: michal-machniak.PNG # add your photo
about-author: I have been passionate about information technology for over 20 years, it is my hobby and my profession. I work as MCT (Certificate owned) / SysOps / Architect / DevOps with customers form different sectors like FinTech, E-commerce, Banking and many more. On my daily work I am building and implementing solutions based on Microsoft technology. In my daily work I use Windows Server, SQL Server, PowerShell, Azure, Office 365, SharePoint, Teams, Azure DevOps, Git ... and many other tools that allow me to complete the task and achieve the goal. # add description
social-twitter: MichalMachniak # add your Twitter handle
social-facebook: michal.machniak # add your Facebook handle
social-github: mimachniak # add your Github handle
social-linkedin: michal-machniak # add your Linkedin handle
social-email: mmachniak@outlook.com # add your Email address

# Disqus
discus-identifier: mmachniak # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
